export const PRODUCTS = [
  { id: 1, 
    slug: "structured-tote",
    name: "Structured Tote", 
    category: "Totes & Shoppers", 
    material: "Calf Leather", 
    colour: "Noir", 
    price: "€2,450",
    src: "/images/WhiteBag.png",
},
  { id: 2, 
    slug: "mini-saddle-bag",
    name: "Mini Saddle Bag", 
    category: "Handbags", 
    material: "Suede", 
    colour: "Camel", 
    price: "€1,890",
    src: "/images/RedBag.png",
},
  { id: 3, 
    slug: "evening-clutch",
    name: "Evening Clutch", 
    category: "Clutches", 
    material: "Satin Leather", 
    colour: "Ivory", 
    price: "€1,200",
    src: "/images/BlackBag.png",
},
  { id: 4, 
    slug: "weekender-tote",
    name: "Weekender Tote", 
    category: "Totes & Shoppers", 
    material: "Grain Leather", 
    colour: "Cognac", 
    price: "€3,100",
    src: "/images/WhiteBagFront.png",
},
  { id: 5, 
    slug: "fold-over-clutch",
    name: "Fold-Over Clutch", 
    category: "Clutches", 
    material: "Calf Leather", 
    colour: "Noir", 
    price: "€980",
    src: "/images/RedBagFront.png",
},
  { id: 6, 
    slug: "crossbody-sling",
    name: "Crossbody Sling", 
    category: "Handbags", 
    material: "Nappa Leather", 
    colour: "Stone", 
    price: "€1,650",
    src: "/images/BlackBagFront.png",
},
  { id: 7, 
    slug: "box-bag",
    name: "Box Bag", 
    category: "Handbags", 
    material: "Calf Leather", 
    colour: "Ivory", 
    price: "€2,200",
    src: "/images/WhiteBag.png",
},
  { id: 8, 
    slug: "market-shopper",
    name: "Market Shopper", 
    category: "Totes & Shoppers", 
    material: "Woven Leather", 
    colour: "Camel", 
    price: "€1,750",
    src: "/images/WhiteBag.png",
},
  { id: 9, 
    slug: "card-holder-clutch",
    name: "Card Holder Clutch", 
    category: "Clutches", 
    material: "Suede", 
    colour: "Stone", 
    price: "€750",
    src: "/images/WhiteBag.png",

},
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}